name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# Permissions nécessaires pour écrire le commentaire
permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Comment Pull Request
        uses: thollander/actions-comment-pull-request@v3.0.1
        with:
          # On concatène les variables : vars pour le prénom, secrets pour le nom
          message: |
            BONJOUR ${{ vars.PRENOM }} ${{ secrets.NOM }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run a one-line script
        run: echo "Le message a été envoyé pour ${{ vars.PRENOM }}."
